version: '2'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: swagger/mongodb
    env_file: .env
    volumes:
      - .docker/mongo/data/db:/data/db
    ports:
      - 27017:27017
  default_controller:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mongodb
    image: swagger/default_controller
    volumes:
      - .:/opt/default_controller
    command: ./bootstrap.sh
    stdin_open: true
    tty: true
    links:
      - mongodb
    ports:
      - 8080:8080